kind: ENC[AES256_GCM,data:iTD+rVWd,iv:7T83+2isDv8YGZ1g2CcFRWrJpTfI4fHUpWYxy2x72YM=,tag:Bjre93PJvixSGhF067ssNw==,type:str]
ansible_user: ENC[AES256_GCM,data:GhiaBBi7fLxJiRc=,iv:sqB2WdyEQNaSl4y2/VJE1CV4/z8KqHYKuAP/Y9zoDAg=,tag:eCZ34SffMFLgmLAX3ERBjQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cyRNMWlavGkpF8E=,iv:ITnkgH2Kzy9yieG22n2bmdjDQxGy7vnei2JfRl5SGi4=,tag:PWBKTH/MP6ME5LGqtQTTQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbFRlN3JkbE44aWpNMzNN
            bzA4eWlzZmp2U2Y2NjV6Nlg3aDJwcmJLTndvCmJGVHdLVkJXMTY4WlBBb0JmdDFZ
            bThxR0xZZys3bmdFNGY0QlJ0QlpmM2cKLS0tIEViUWdDbnZRM3E5bThMMnBHeDFh
            bjkzUHg1VDVwMnJVem9EWWVaNFl0WlkKEf9wV+48DExYCie5onhii5/MyT/ql2Qu
            6pmbkULZ2I8jGXoS6lmpQMuD2QZR06SUPhXk+VjQnPcLJ2JEDi/Yog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T02:35:41Z"
    mac: ENC[AES256_GCM,data:IO7IEJGOA/rbkKGsTLifrbBDgdKUFywMS55D5BLHbAn3y7snhygL9xvEA8ixzINAF/UGhdI0T2EhBH8mweCyXxcXvXFf2JEZm525QdJMn4h4oAyfkzPLKilcU5SVFIL2QNe0C2nDnMdkq+ku56X9Gtj49AtNwj7Pa5Mngzb46W8=,iv:BepLRtl5h+CSI6z7u4hNNFk+lC4fypiImpFQoHFhC58=,tag:B5REJvDRYoBzDbSOEeob9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
