kind: ENC[AES256_GCM,data:oZwDv6u8,iv:0pyelOQ4yViXXdUbS4dNiEYEPj8z87+5SPHx2iDmNl8=,tag:cpfqOKOTo2BPZYXcygPbhw==,type:str]
ansible_user: ENC[AES256_GCM,data:Ku8/AZjzKIt8QE8=,iv:w1X0s7WuENFOXvehaEoA8ihaWNywNkUzkz7ycpHYQec=,tag:/1Et+nPapCj+mByFcNFLgw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tPQBhCHby6KDQTA=,iv:40aTlvEL72U90ZOJhydn9JlQaShyWd8/7719AisMOxE=,tag:MSJBg3drf6MZVKIamqcL5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdGRpTDNCRitydDF5NkZN
            QmkrOVlvam5yd2ZNZzlLSnZOeTRhTTVoNmpBClJpT3U2a25rbnpiQ1lOZ3FGNExV
            VU9TaU1nUTY1citYVG5JaTBKZVkxakkKLS0tIDFYM3BNUWN3TDg2QXVROHRrTDRP
            dGtTQnl4UEZ2clV4Tm1kQTZGV3lva00KroXTmu0qnkd8gLS1mql2N67km0SBRdeK
            QHpUehWwrxgDHqdDNL979SR2bmiTa/+uDWumY69AYRtziCARnDeE7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T02:35:41Z"
    mac: ENC[AES256_GCM,data:17dklrJMySHVeW7A/3k/NTkubh2KlmKicQOAd5Xi04gqRDA3ZJ0gEEbde8Gz8ebprUSr8ZmyB3tY/16rkOf95LdIEUVi9f2xUHuWUQO8KOa5lA6yGYeLSBHlXfdyszSGGgQrCV7d6ygEg47x3bxV/Gf+yt2BP40O8V4JkweUCng=,iv:wd6vGH6Y0qdw8BXhAdYi6X9D4fSkKh/DABxIPuEcRck=,tag:DHNLkjSsAfJJm8j8nzbSdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
