kind: ENC[AES256_GCM,data:s79HdZXB,iv:Kv0wo+5cC+hrYlCyypWBb1e3KBNGXxdZ2hkZz8Os3Sw=,tag:j9wfPr2LRnf8ViGOhobFDA==,type:str]
ansible_user: ENC[AES256_GCM,data:GtUhQH8QJL0x0Gw=,iv:uUDkmoQEEZaA6stW3tgEdyjjHc+SZqAKbI/RjfBer1U=,tag:fF3XhVOLpRWYgW/iPs6yBQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5bdt250ZLhWm/6Y=,iv:Lyvgam66YY2L8rtnkvhYThQjA2qOqDwG0H021iuKLKw=,tag:ycx0e2uY/C0fOWNWYSXtQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaVlzWFU2Wm9qZ1lKQlp4
            ZllXbVZDb0w4SlRqR2s3MnhFcmhEZGYzbkhBCjdabGtkamxXRFQ3NzhwN1FVRGxV
            Z3Mvb2FDbU53RXRZSGRyNHZVOE5QTFEKLS0tIGRwS2dwRS9UR2FWSHhFcWhRck96
            SG1wRkE1dE5vM2hjTVNzamZHcXplTnMKZg0e7R3+VSjuqpza89w73lqfY1hEpoFS
            lRC730PYFL0KOCxsFIa2TBMc2V+LAWFZTos/W11e5xFrKJa8NkD8Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T02:32:22Z"
    mac: ENC[AES256_GCM,data:VDDHxtxVcNIdqAcAY5eknEZm0D68tsnihWsD3GYwD6eyRDYFrHtaC4JKs8+PEzYNSpga9oyTYN5x7T8F0uE1ndlaNwotbGwjsblwufvf2upspsaxy5SKufuNWD3eYy2wYMS2b7B7n7FJXKN3YDL0MjzGc0ZsQlGqHRzBusOuBXk=,iv:Yqv8yvn+srtekV8WxHs4EWV1/BmjRD8wmZvnmU8SwOs=,tag:WC8OCnb2JIGeA5MjKo1FnA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
