kind: ENC[AES256_GCM,data:l2Qa7Z2B,iv:8bm9VSibzlybVYlsJZejguxAU8QGM9bwL70Cq1vbNlw=,tag:z3OWuYlV2UGvoBk+VGvUSw==,type:str]
ansible_user: ENC[AES256_GCM,data:zbCOnXA+1yyw2uM=,iv:7DXmATA3VxYRufn/oAOnU2DTq4V1cVBpE6VmAKKzmSE=,tag:5W7AG2c2JeVCSJkJHJxsEA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:63BRK5roXjiZMlM=,iv:m55x3XAGUWPHYuCtMaecnY9XM8h0crir1Yv6TL+tqVs=,tag:pZ+djlFr4jJG/evShYMkug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd25mbXRyVDU4T05JM1da
            L3ZnN013Q2pnRnlDREgwMXdrVktvWWRnMzMwCnZGYXhWcWNKVUVkYjF6SVZSSE9q
            RjZNZDZVeVJoK3V6MUlMd1h0OThsK2sKLS0tIDJJY3hERHh2aXY2WU1mblYyZEtV
            SHRjdFZoaU10Wmx1b3FJQmo3TG1IdXcK7pTCeGIxwYLerOcZKwGQOei6H7wj0stS
            kdNDoO9dQwKkkLY0XMVHXuPDEjuukZa8aaHiR/FxH4sNk1pzAw2UAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T20:40:23Z"
    mac: ENC[AES256_GCM,data:vupRR/qYvSMQ8XDP2XBNX4+Tr4PvOTkjWsJLnt/fLGzCAaylZGlMEPUvVyLxDCmso7LLbisiP4nzBer0gk7VKnEl/8heXXONod2Xl+EOU12YW+8PsMVkuErs8eL3koDPLq7vEroIIeqdYOWF+1jVQKnRHhZpdRDDwNZL1LIUWqY=,iv:DZkw9tgBe85/ltUoVlB6REPomeLhBbC7zDYuqn5Qv3E=,tag:xwfERuFVtPHQjTciLPQFLw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
