kind: ENC[AES256_GCM,data:5Ga5k4Lz,iv:1OAXH2jodaKaspRjsxR/FEXFTwIwi1RunfDfir76pok=,tag:y3UjuYl6Z7EW/tKCSMeyYQ==,type:str]
ansible_user: ENC[AES256_GCM,data:7mTqk1eH3qscQwM=,iv:CkjuTN1X/4N33x8GOhnxNrge/EHC6lDEBcMpR8ftylw=,tag:447abobva8jStkENHH/56Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:994SF/MQ9tsOXrA=,iv:bC85GZuwq6B8qHrXXh0umB7GRseuFUo+NN2wv1U5szA=,tag:Na5h39xC9nMZ2mGCyDczEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWFpydXE0NXNObnl5Wjd2
            emlhUGtJZW5wL0wrWjNabzZCa1p1WEY2NWpVCmtzUnhjTFBDME4zSUU0QldMQXFK
            S3duVGpQLy9zK1k2V2tDeUJrblBaSkkKLS0tIEl0ZS9WUHhCRVNOUDRhS0N2K1VE
            ZFNkMjR3Z3BNUzZCVDBxVlhEcEdDcjQKOTo/D7YOLGSVAROq/iRpaCs1DI1Btpo4
            qQ9pjB1a6NKkFla5vKhhHIYZY7FowjlQ6S534ZY7HSvBA201xvO7BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-25T21:14:14Z"
    mac: ENC[AES256_GCM,data:EscqG/+toNipUGYBJ5wBqruDHpazVJK0dPZum96vA+5oZeDWl9Wi01Tb7dUAMu4JW2dUpta/3kPxNxOy8CyKXvIELxnH47zBRLZg1+hGHxzD6BrqUSfKs4FvNt1sWAsApYYICFtGJ6nDKrD/QscgsSmxbiryqrNEyearaWtqibA=,iv:drPDk5eVOG7znm3KWmIi7DNmK3sVBWYqjGhUWrLfnuE=,tag:YjxRm8g1AC9y96vCnFdqJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
