kind: ENC[AES256_GCM,data:b57dJBE5,iv:l9fUxSI8yhwIz0NkQ+uM268PdIVBamLu+hr4kLQI/Xo=,tag:Io2coJGBvCbp3m33VAZ2Kw==,type:str]
ansible_user: ENC[AES256_GCM,data:QOPbSBB9SgerLNw=,iv:YwoA07jsHuS6PNknow5k8OrPv+cAKmg6mNp4sLG8u7c=,tag:yFNG5zOtpFEwOaMOOAEJ7Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Zh6ay/zRl2keb38=,iv:4RahpIrSCIvdAN4lv9iWQ0T1djqk9YTRTd4OPWHlHWs=,tag:ohffQbXI2UAMkloV09b0Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd1I0N1hieG9jRXBxZEFp
            YXNrNlpmeTJYekdwZWpnWHY3dGo3TU0vbm5ZCndGcW9FbjZDUWNtZHR1YlF6TmhZ
            WDVMRmlZUFFuRHlrcnpsMHZzeDdZWUkKLS0tIERTRk12b2JCLzRnQWljU25OVHhs
            R005ZVg1dlNqd0g4aVl1TnV4elhibUkKOH36g3owQ2Ia9L2UuKVjCTMcs6G7v8zM
            o0CUS+lqOc3wXN34CUMY+aBr2HJh69aQYWcJBk/y4HHbGMbKItIZvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T02:35:41Z"
    mac: ENC[AES256_GCM,data:mMRFIS5woPbHgVbYpyeShlDdfeSvzTMGxTbjxu5qCDJAstAK6dfuHTVSi026ixER6GteXb+oMRTC79r3B2g4TrigUYBQ40tkDj4PkALndYBbuNlQxM1M0WzG8iHCt4aXIX2waW5xv4/nyR4EkZmaphUcVMVLni01GJvd6ujxcl8=,iv:tCq1ISKRicRAW392wRzgPyOTVXedR2s7bWnoNWRonT8=,tag:afYhY0tFSba4rywVIkjE3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
