apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:du6dtQun+WDJmjPqQHwK0zyfWLR1p8S4KWqJ9hxCv+wMbm0l0g==,iv:61ajIpS8BQ+MtIDJiwXX/saeT9pNBwUVRZJyiqUR3UY=,tag:/FzBDJO8HjipgrHB5EUjoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYUxjTTBNWG5CaGdobGth
            Wjk5eCt2eDBDVk16blR2RXF1dWpVb1FoZ3cwCkI3WUNOMm9obnJncks4L0JjdE5I
            dkNhRGxJbVFOdEVkVjdvSnRGNUlua1UKLS0tIHFHNjZ0SEZyWXpxMUpibjRqbDhy
            eUVDb204alE4VDFlSVdvUXB1dEVVV0kKFSBTRigKcmRezEcMIMuBuwY69FFoBpe4
            VS3fe2pF6ErT2tOTbDxkrcotcsO98yoNia5trzRkewmDzM5q6i59fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T02:35:40Z"
    mac: ENC[AES256_GCM,data:SL4aseKPZY66vH5m0DwT/we7TQivHc+Q+cWdFljac0BMYTHI/QS3Q5JSCM8LXaEI6YSD0cYeCCr+TxN1WBZO2czgN+uXLQnb9dHhMVoRiC7TpQD0dPi6U3ezKJtg4W3A4AbcMw5dgyW+s5FYwqThKCQMrhylFSYmrGj1Xd+l0zc=,iv:0damVubnJSEOJjlXqAus0w1UoD83Q1xGfDWFdPsKzhQ=,tag:pUls/5ymKihPy3h2iBIITg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
