apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:EBuvJyqNnAW6rzZQ6/VBE1E9+c9k7zC41pCms9AmF5QLDmkvYQ==,iv:XpYRnFIA2E8vLJ7HRZL0cHYXN6dZExR/g0OEmaEVnGE=,tag:rHVxoXC2LgT4aWuKFbDBNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb01heWF4N1pVVUlyenEw
            Y1luYU5Od0Qrc2tBQmxkTDA1SXdPRVRKNUNRCktWVVc5OVZUaTNCTmMzdU5OZWpD
            c2pCRmdkb2xTVThlbWIvNXVyUzB6QkUKLS0tIDhLeTRTZGVmVEUzMEE1TDUzaFg2
            R0s5NkhtRHJPTXYwaTA3MVEwRWpnMjAK9skqprsNznxdW8k/7XTgcc24FOYAWM7p
            az94leZODLRiuKgVKPWeSUnWweZ7MBcUty/duD2XEJJlxwgoHPDT6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T02:32:22Z"
    mac: ENC[AES256_GCM,data:uJxrtkLISvFCK2b5ALJgoY2wCeJorQGAAksUe08BFQtWkWB8Y8xQi6gY0F52l57JylxfVkbycntmel7iWjI/1SxWumKl3GquxoEY1lfav2vRPirkZlmxjvjEjUzdlnbdDp611gCyRGdDUxmqmSt7Kj8ht7Tt20V3akF2m8WGiNI=,iv:T9aNRsyKWm9maimlCNv3SBgJ3WIYgnHYedvrij7gHEY=,tag:qX3yHU3gP5zx6xwwRbX0Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
