apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:IY/D0D9rfLKc8jgZCeiQOa6Cjg==,iv:Bj8PPzutqqq/BTAzSZ4mHMeu0jBdJyPCNpbNQYd4Kg4=,tag:tjCEvC0BXjjykqfSlhq77g==,type:str]
    api-key: ENC[AES256_GCM,data:ffQ4CmEpe1bFRVgXVAQ6xobJodP8eSLJWlJ3qjyFMrWZeVbuhA==,iv:XtWNJupx3yW3GR2jwP3TbXTGnfD29bDjgRm1ie1XeRA=,tag:Qrp9YSiZ2TYyISIPdctGug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shmlaytvhwattuyqaqavqnjngzrh9cuds33k7jfp7kxsunfs9u7ql3k4mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNmRUcGhxOTl6REpqa3Ux
            UXEvNVJVU2ZIclNBWU9MUWJNUEdNUWgvbVFrCmkrMzVVQnNDV2FZdDdZV1piakVi
            T2lIdXVLOUZBeU9jYVVqdGlKMEFDckkKLS0tIGV3d0l2c0piZkJzcnlrSW44clc3
            ZCtWcFUyN1gxa0MraVFOcHJuTlp0aFkKeLLwk8O0W4DejAQuibC5hCDXR60WkHfl
            Feo+9mn1+8mWUCyl3yJaOClVWbZjq0rn4yXFHEIyYyEMRQWnZNoX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T02:35:40Z"
    mac: ENC[AES256_GCM,data:BHOltlaNX9iFxPcS1frnBaNWr8u9JvXpDX/VyaZrnoJRuAz3/450XoU6lQNs6V66lNrQspOkE5c6nQQVg/qN20A6hEFqJmeoGonzx56RdEOl9vKMA+HTmqvBpwCiNnLJpPlJRPMqgUdPKXvgteP7fX2UEj90pZZ96ZqYiiRr3GA=,iv:XkZivlqtpVBv4icslV9RDcrNO6WbP2u8WJVBL17OvpM=,tag:7jEO26/WkwguKMiRXgNVTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
