---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "10.10.10.100"
  METALLB_LB_RANGE: "10.10.10.50-10.10.10.60"
  METALLB_K8S_GATEWAY_ADDR: "10.10.10.50"
  METALLB_INGRESS_ADDR: "10.10.10.51"
